### ISSUE TITLE
Issue Editing the layer "gc_punti_prelievo"

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C098#74]
As reported by the client **it seems** that after the latest update of GeoServer there is a problem while editing the layer **gc_punti_prelievo**:

The layer is availabla in this map:

http://webgis.sir.toscana.it/mapstore/#/viewer/openlayers/397

If you try to edit the layer mentioned above, the following error occurs:

```
<?xml version="1.0" encoding="UTF-8"?><ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/ows http://wms.cfr.toscana.it/geoserver/schemas/ows/1.0.0/owsExceptionReport.xsd">
<ows:Exception exceptionCode="InvalidParameterValue">
<ows:ExceptionText>Feature type 'gc_punti_prelievo' is not available: </ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
```

**Comment by randomorder** [comment]
Initial feedback


Request from MS2 (logged in as admin):
```
http://webgis.sir.toscana.it/mapstore/proxy/?url=http%3A%2F%2Fwms.cfr.toscana.it%3A80%2Fgeoserver%2Fgenicivili%2Fwfs%3Fauthkey%3D5xxxxxxxxxxx
```

GeoServer log
```
2020-04-21 16:37:26,492 DEBUG [org.geoserver.security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /genicivili/wfs, QueryString: authkey=xxxxxxxxxxx'; against '/web/**'
2020-04-21 16:37:26,492 DEBUG [org.geoserver.security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /genicivili/wfs, QueryString: authkey=xxxxxxxxxxx'; against '/gwc/rest/web/**'
2020-04-21 16:37:26,492 DEBUG [org.geoserver.security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /genicivili/wfs, QueryString: authkey=xxxxxxxxxxx'; against '/'
2020-04-21 16:37:26,492 DEBUG [org.geoserver.security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /genicivili/wfs, QueryString: authkey=xxxxxxxxxxx'; against '/j_spring_security_check'
2020-04-21 16:37:26,492 DEBUG [org.geoserver.security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /genicivili/wfs, QueryString: authkey=xxxxxxxxxxx'; against '/j_spring_security_check/'
2020-04-21 16:37:26,492 DEBUG [org.geoserver.security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /genicivili/wfs, QueryString: authkey=xxxxxxxxxxx'; against '/j_spring_security_logout'
2020-04-21 16:37:26,492 DEBUG [org.geoserver.security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /genicivili/wfs, QueryString: authkey=xxxxxxxxxxx'; against '/j_spring_security_logout/'
2020-04-21 16:37:26,492 DEBUG [org.geoserver.security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /genicivili/wfs, QueryString: authkey=xxxxxxxxxxx'; against '/rest/**'
2020-04-21 16:37:26,492 DEBUG [org.geoserver.security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /genicivili/wfs, QueryString: authkey=xxxxxxxxxxx'; against '/gwc/rest/**'
2020-04-21 16:37:26,492 DEBUG [org.geoserver.security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /genicivili/wfs, QueryString: authkey=xxxxxxxxxxx'; against '/**'
2020-04-21 16:37:26,492 DEBUG [org.geoserver.security.IncludeQueryStringAntPathRequestMatcher] - Request matched by universal pattern '/**'
2020-04-21 16:37:26,492 DEBUG [org.geoserver.security.IncludeQueryStringAntPathRequestMatcher] - Matched Path: /genicivili/wfs, QueryString: authkey=xxxxxxxxxxx with /**
2020-04-21 16:37:26,495 DEBUG [org.geoserver.geofence] - Getting access limits for workspace genicivili
2020-04-21 16:37:26,495 DEBUG [org.geoserver.geofence] - Getting access limits for workspace genicivili
2020-04-21 16:37:26,495 DEBUG [org.geoserver.geofence] - Getting access limits for workspace genicivili
2020-04-21 16:37:26,495 DEBUG [org.geoserver.geofence] - Getting access limits for workspace genicivili
2020-04-21 16:37:26,495 DEBUG [org.geoserver.geofence] - Getting access limits for workspace genicivili
2020-04-21 16:37:26,495 DEBUG [org.geoserver.geofence] - Getting access limits for workspace genicivili
2020-04-21 16:37:26,495 TRACE [org.geoserver.ows.OWSHandlerMapping] - Mapped to HandlerExecutionChain with [org.geoserver.ows.Dispatcher@7ca95533] and 4 interceptors
2020-04-21 16:37:26,495 DEBUG [org.vfny.geoserver.requests] - First 4 bytes of XML doc are : 3C ('<') 77 ('w') 66 ('f') 73 ('s')
2020-04-21 16:37:26,495 DEBUG [org.vfny.geoserver.requests] - Charset detection phase 1. Inferred encoding: UTF-8
2020-04-21 16:37:26,495 DEBUG [org.vfny.geoserver.requests] - Invalid(?) XML declaration: <wfs:T.
2020-04-21 16:37:26,495 DEBUG [org.vfny.geoserver.requests] - Charset detection phase 2. Charset in XML declaration is `null`.
2020-04-21 16:37:26,495 DEBUG [org.vfny.geoserver.requests] - Trying to create reader basing on existing charset information: `UTF-8`.
2020-04-21 16:37:26,495 DEBUG [org.geoserver.ows] - Raw XML request: <wfs:Transaction service="WFS" version="1.1.0" xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs" xmlns:genicivili="www.cfr.toscana.it/genicivili"><wfs:Update typeName="genicivili:gc_punti_prelievo"><wfs:Property><wfs:Name>gestore</wfs:Name><wfs:Value><![CDATA[CAMPIMG RADA ETRUSCA DI GIANNOTTI DANTE & C. S.N.C..]]></wfs:Value></wfs:Property><ogc:Filter><ogc:FeatureId fid="gc_punti_prelievo.28716"/></ogc:Filter></wfs:Update></wfs:Transaction>���������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
2020-04-21 16:37:26,495 DEBUG [org.geoserver.geofence] - Getting access limits for workspace genicivili
2020-04-21 16:37:26,495 INFO [org.geoserver.wfs] - 
Request: getServiceInfo
2020-04-21 16:37:26,497 WARN [org.geotools.xsd] - Sax parser property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' not recognized.  Xerces version is incompatible.
2020-04-21 16:37:26,497 WARN [org.geotools.xsd.impl] - Schema location not specified as namespace/location pair. Ignoring http://www.opengis.net/wfs
2020-04-21 16:37:26,497 WARN [org.geotools.xsd.impl] - Could not find a schema
2020-04-21 16:37:26,497 DEBUG [org.geoserver.geofence] - Getting access limits for workspace genicivili
2020-04-21 16:37:26,498 DEBUG [org.geoserver.geofence] - Getting access limits for workspace genicivili
2020-04-21 16:37:26,498 INFO [org.geoserver.flow] - Request [WFS 1.1.0 Transaction] starting, processing through flow controllers
2020-04-21 16:37:26,498 DEBUG [org.geoserver.flow] - Request [WFS 1.1.0 Transaction] checking flow controller BasicOWSController(wfs.getfeature.=application/msexcel,org.geoserver.flow.controller.SimpleThreadBlocker@44620ad2)
2020-04-21 16:37:26,498 DEBUG [org.geoserver.flow] - Request [WFS 1.1.0 Transaction] passed flow controller BasicOWSController(wfs.getfeature.=application/msexcel,org.geoserver.flow.controller.SimpleThreadBlocker@44620ad2)
2020-04-21 16:37:26,498 DEBUG [org.geoserver.flow] - Request [WFS 1.1.0 Transaction] checking flow controller BasicOWSController(gwc,org.geoserver.flow.controller.SimpleThreadBlocker@5f26fc5b)
2020-04-21 16:37:26,498 DEBUG [org.geoserver.flow] - Request [WFS 1.1.0 Transaction] passed flow controller BasicOWSController(gwc,org.geoserver.flow.controller.SimpleThreadBlocker@5f26fc5b)
2020-04-21 16:37:26,498 DEBUG [org.geoserver.flow] - Request [WFS 1.1.0 Transaction] checking flow controller org.geoserver.flow.controller.UserConcurrentFlowController@77f9f4f2
2020-04-21 16:37:26,498 DEBUG [org.geoserver.flow] - UserFlowController(12,GS_CFLOW_-6e359db6:17108414187:-2307) queue size 1
2020-04-21 16:37:26,498 DEBUG [org.geoserver.flow] - UserFlowController(12,GS_CFLOW_-6e359db6:17108414187:-2307) total queues 3
2020-04-21 16:37:26,498 DEBUG [org.geoserver.flow] - UserFlowController(12) purged 2 stale queues
2020-04-21 16:37:26,498 DEBUG [org.geoserver.flow] - Request [WFS 1.1.0 Transaction] passed flow controller org.geoserver.flow.controller.UserConcurrentFlowController@77f9f4f2
2020-04-21 16:37:26,498 DEBUG [org.geoserver.flow] - Request [WFS 1.1.0 Transaction] checking flow controller BasicOWSController(wms.getmap,org.geoserver.flow.controller.SimpleThreadBlocker@279e5017)
2020-04-21 16:37:26,498 DEBUG [org.geoserver.flow] - Request [WFS 1.1.0 Transaction] passed flow controller BasicOWSController(wms.getmap,org.geoserver.flow.controller.SimpleThreadBlocker@279e5017)
2020-04-21 16:37:26,498 DEBUG [org.geoserver.flow] - Request [WFS 1.1.0 Transaction] checking flow controller GlobalFlowController(org.geoserver.flow.controller.SimpleThreadBlocker@17d5ace8)
2020-04-21 16:37:26,498 DEBUG [org.geoserver.flow] - Request [WFS 1.1.0 Transaction] passed flow controller GlobalFlowController(org.geoserver.flow.controller.SimpleThreadBlocker@17d5ace8)
2020-04-21 16:37:26,498 INFO [org.geoserver.flow] - Request control-flow performed, running requests: 1, blocked requests: 0
2020-04-21 16:37:26,499 DEBUG [org.geoserver.geofence] - Getting access limits for workspace genicivili
2020-04-21 16:37:26,499 DEBUG [org.geoserver.wfs] - Locating FeatureSource uri:'www.cfr.toscana.it/genicivili' name:'gc_punti_prelievo'
2020-04-21 16:37:26,499 DEBUG [org.geoserver.geofence] - Getting access limits for Resource gc_punti_prelievo
2020-04-21 16:37:26,499 DEBUG [org.geoserver.geofence] - Setting user for filter: anonymous
2020-04-21 16:37:26,499 DEBUG [org.geoserver.geofence] - ResourceInfo filter: RuleFilter[user:"anonymous"+ role:ANY inst:name+:default-gs ip:"10.159.212.110"+ serv:"WFS"+ req:"TRANSACTION"+ ws:"genicivili"+ layer:"gc_punti_prelievo"+]
2020-04-21 16:37:26,499 DEBUG [org.geoserver.geofence.cache] - Request for RuleFilter[user:"anonymous"+ role:ANY inst:name+:default-gs ip:"10.159.212.110"+ serv:"WFS"+ req:"TRANSACTION"+ ws:"genicivili"+ layer:"gc_punti_prelievo"+]
2020-04-21 16:37:26,499 DEBUG [org.geoserver.geofence.cache] - Loading RuleFilter[user:"anonymous"+ role:ANY inst:name+:default-gs ip:"10.159.212.110"+ serv:"WFS"+ req:"TRANSACTION"+ ws:"genicivili"+ layer:"gc_punti_prelievo"+]
2020-04-21 16:37:26,499 INFO [org.geoserver.geofence.services.RuleReaderServiceImpl] - Requesting access for RuleFilter[user:"anonymous"+ role:ANY inst:name+:default-gs ip:"10.159.212.110"+ serv:"WFS"+ req:"TRANSACTION"+ ws:"genicivili"+ layer:"gc_punti_prelievo"+]
2020-04-21 16:37:26,518 DEBUG [org.geoserver.geofence.internal] - Checking UserGroupService [default]
2020-04-21 16:37:26,518 DEBUG [org.geoserver.geofence.internal] - Checking UserGroupService [geostore]
2020-04-21 16:37:26,533 DEBUG [org.geoserver.geofence.internal] - Matching Roles [[]] for User [anonymous]
2020-04-21 16:37:26,542 DEBUG [org.geoserver.geofence.services.util.FilterUtils] - ADDED Rule[id:2 pri:5 srv:WFS req:TRANSACTION acc:DENY]
2020-04-21 16:37:26,542 DEBUG [org.geoserver.geofence.services.util.FilterUtils] - ADDED Rule[id:4 pri:6 acc:ALLOW]
2020-04-21 16:37:26,542 DEBUG [org.geoserver.geofence.services.RuleReaderServiceImpl] - Filter RuleFilter[user:"anonymous"+ role:ANY inst:name+:default-gs ip:"10.159.212.110"+ serv:"WFS"+ req:"TRANSACTION"+ ws:"genicivili"+ layer:"gc_punti_prelievo"+] is matching the following Rules:
2020-04-21 16:37:26,542 DEBUG [org.geoserver.geofence.services.RuleReaderServiceImpl] -     Role:ROLE_ANONYMOUS
2020-04-21 16:37:26,542 DEBUG [org.geoserver.geofence.services.RuleReaderServiceImpl] -     Role:ROLE_ANONYMOUS ---> Rule[id:2 pri:5 srv:WFS req:TRANSACTION acc:DENY]
2020-04-21 16:37:26,542 DEBUG [org.geoserver.geofence.services.RuleReaderServiceImpl] -     Role:ROLE_ANONYMOUS ---> Rule[id:4 pri:6 acc:ALLOW]
2020-04-21 16:37:26,542 DEBUG [org.geoserver.geofence.services.RuleReaderServiceImpl] - Filter RuleFilter[user:"anonymous"+ role:ANY inst:name+:default-gs ip:"10.159.212.110"+ serv:"WFS"+ req:"TRANSACTION"+ ws:"genicivili"+ layer:"gc_punti_prelievo"+] on role ROLE_ANONYMOUS has access AccessInfoInternal[grant:DENY]
2020-04-21 16:37:26,542 WARN [org.geoserver.geofence.services.RuleReaderServiceImpl] - No access for filter RuleFilter[user:"anonymous"+ role:ANY inst:name+:default-gs ip:"10.159.212.110"+ serv:"WFS"+ req:"TRANSACTION"+ ws:"genicivili"+ layer:"gc_punti_prelievo"+]
2020-04-21 16:37:26,542 INFO [org.geoserver.geofence.services.RuleReaderServiceImpl] - Returning AccessInfo[grant:DENY admin:false] for RuleFilter[user:"anonymous"+ role:ANY inst:name+:default-gs ip:"10.159.212.110"+ serv:"WFS"+ req:"TRANSACTION"+ ws:"genicivili"+ layer:"gc_punti_prelievo"+]
2020-04-21 16:37:26,542 DEBUG [org.geoserver.geofence] - Returning mode HIDE for resource FeatureTypeInfoImpl[gc_punti_prelievo]
2020-04-21 16:37:26,542 DEBUG [org.geoserver.geofence] - Returning VectorAccessLimits [readAttributes=null, writeAttributes=null, writeFilter=Filter.EXCLUDE, readFilter=Filter.EXCLUDE, mode=HIDE] for layer genicivili:gc_punti_prelievo and user null
2020-04-21 16:37:26,542 DEBUG [org.geoserver.geofence] - Getting access limits for workspace genicivili
2020-04-21 16:37:26,542 ERROR [org.geoserver.ows] - 
org.geoserver.wfs.WFSTransactionException: Feature type 'gc_punti_prelievo' is not available: 
	at org.geoserver.wfs.Transaction.execute(Transaction.java:191)
	at org.geoserver.wfs.Transaction.transaction(Transaction.java:92)
	at org.geoserver.wfs.DefaultWebFeatureService.transaction(DefaultWebFeatureService.java:147)
	at sun.reflect.GeneratedMethodAccessor927.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.geoserver.ows.util.RequestObjectLogger.invoke(RequestObjectLogger.java:50)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy151.transaction(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor926.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.geoserver.ows.Dispatcher.execute(Dispatcher.java:879)
	at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:265)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:998)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:901)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:875)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:69)
	at org.geoserver.flow.controller.IpBlacklistFilter.doFilter(IpBlacklistFilter.java:89)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
	at org.geoserver.flow.ControlFlowCallback.doFilter(ControlFlowCallback.java:260)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
	at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:73)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
	at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:41)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:37)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:51)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
	at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:52)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:142)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.geoserver.filters.XFrameOptionsFilter.doFilter(XFrameOptionsFilter.java:79)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:42)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1504)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1460)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```
(By the way. I found GeoServer log level set to VERBOSE)

Looks like I am not recognized as an Admin by GeoFence so I am not allowed to make the transaction by GeoFence rules

![image](https://user-images.githubusercontent.com/5264230/79880249-0e170200-83f0-11ea-8061-e1418288a6ef.png)

I am able to edit the feature using BAsic Auth from QGis so I suspect there is something going on with either Authkey or Role Service. I'll keep on investigating and get back to you

**Comment by randomorder** [comment]
Authkey service seems to be ok
```
curl -v "http://localhost:8081/mapstore/rest/geostore/session/username/xxxxxxxxxx"
*   Trying ::1...
* Connected to localhost (::1) port 8081 (#0)
> GET /mapstore/rest/geostore/session/username/xxxxxxxxxx HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Cache-Control: no-cache
< Expires: -1
< Date: Tue, 21 Apr 2020 14:30:26 GMT
< Content-Type: text/plain
< Content-Length: 5
< 
* Connection #0 to host localhost left intact
admin
```

Roles are looking good too
![image](https://user-images.githubusercontent.com/5264230/79883576-618b4f00-83f4-11ea-9347-3bce363963c1.png)

Can we ask Alessio to take a look at GeoFence logs @tdipisa ?

**Comment by randomorder** [comment]
I got the following exception when navigating the UI of the SIR GeoServer
![image](https://user-images.githubusercontent.com/5264230/79891343-280d1080-8401-11ea-9c9f-c4631a3dbf5c.png)
![image](https://user-images.githubusercontent.com/5264230/79891328-23485c80-8401-11ea-95f0-072ff75be72d.png)
![image](https://user-images.githubusercontent.com/5264230/79891384-31967880-8401-11ea-80d9-842e58798470.png)

I think we need a DEV to take a look at this @chpicone

**Comment by chpicone** [comment]
Hi @aaime can you take a look at this problem?

**Comment by chpicone** [comment]
@simboss do you think it is possible that @aaime could will take a look at this?

**Comment by chpicone** [comment]
Focusing on this part of the Geoserver log:

>  [org.geoserver.geofence] - Setting user for filter: **anonymous**
>  [org.geoserver.geofence] - Returning VectorAccessLimits [readAttributes=null, writeAttributes=null, writeFilter=Filter.EXCLUDE, readFilter=Filter.EXCLUDE, mode=HIDE] for layer genicivili:gc_punti_prelievo and **user null**

and considering that the security>authentication page reports this error:

> Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: authKeyAuthentication

 I think it is necessary to investigate why Geoserver/Geofence is not able to correctly recognize the user.

**Comment by chpicone** [comment]
Discussing con @tdipisa we are thinking on a deploy problem.
Anyway we need to another check on the(accessing from the command line) to evaluate:

- correct comunication from Geoserver to MapStore
- version of the AuthKey module (re-confirm if it is the same of the TIX environment)
- correct configuration of the AuthKey module
- status of the DATA_DIR

@randomorder can you check the previous items?

After those (and after scheduling a stop of Geoserver with the client) we can try:
- memory dump
- restart of the Geoserver
- reinstall the AuthKey module using the jar existing on the TIX server (working)

We've tried to change the log level to VERBOSE and this does not appear in the log.

**Comment by randomorder** [comment]
Hi @chpicone @tdipisa
There is a discrepancy between SIR and TIX geoserver installations:
https://www.diffchecker.com/VMDVhkZ9

I'll have @giacomoc92 take a look and fix

**Comment by randomorder** [comment]
@giacomoc92 It goes without saying that any service interruption must be scheduled with the client. Please get in touch with @chpicone about this

**Comment by chpicone** [comment]
@giacomoc92 we've scheduled service interruption with the customer at 27 April 2020 9.30-11.30 in order to fix the server.

**Comment by giacomoc92** [comment]
@randomorder  the operation started as scheduled and the geoservers are now alligned

**Comment by chpicone** [comment]
I've checked on Geoserver and the Authentication module now shows properly the configuration page.
I've checked on MapStore the WFS feature editing and it now works correctly.

**Comment by randomorder** [comment]
Looking good for me. Waiting for feedback from the client

**Comment by chpicone** [comment]
It works also for the customer.
